services:

  # ---------------- EUREKA SERVER ----------------
  eurekaserver:
    image: varshithreddy144/ecom-eurekaserver:latest
    container_name: eurekaserver
    ports:
      - "8761:8761"
    networks:
      - ecommerce-network

  # ---------------- MICROSERVICE DB ----------------
  microservice-db:
    image: postgres:15
    container_name: microservice-db
    environment:
      POSTGRES_DB: microservicedb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - microservice-db-data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  # ---------------- SECURITY DB ----------------
  security-db:
    image: postgres:15
    container_name: security-db
    environment:
      POSTGRES_DB: securitydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - security-db-data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  # ---------------- AUTH USER SERVICE ----------------
  authuser:
    image: varshithreddy144/ecom-authuserapi:latest
    container_name: authuser
    ports:
      - "9090:5000"
    depends_on:
      - eurekaserver
      - security-db
    networks:
      - ecommerce-network

  # ---------------- ADMIN SERVICE ----------------
  adminapi:
    image: varshithreddy144/ecom-adminapi:latest
    container_name: adminapi
    depends_on:
      - eurekaserver
      - microservice-db
    networks:
      - ecommerce-network

  # ---------------- CUSTOMER SERVICE ----------------
  customerapi:
    image: varshithreddy144/ecom-customerapi:latest
    container_name: customerapi
    depends_on:
      - eurekaserver
      - microservice-db
    networks:
      - ecommerce-network

  # ---------------- PRODUCT SERVICE ----------------
  productapi:
    image: varshithreddy144/ecom-productapi:latest
    container_name: productapi
    depends_on:
      - eurekaserver
      - microservice-db
    networks:
      - ecommerce-network

  # ---------------- CART SERVICE ----------------
  cartapi:
    image: varshithreddy144/ecom-cartapi:latest
    container_name: cartapi
    depends_on:
      - eurekaserver
      - microservice-db
    networks:
      - ecommerce-network

  # ---------------- ORDER SERVICE ----------------
  orderapi:
    image: varshithreddy144/ecom-orderapi:latest
    container_name: orderapi
    depends_on:
      - eurekaserver
      - microservice-db
    networks:
      - ecommerce-network

  # ---------------- API GATEWAY ----------------
  apigateway:
    image: varshithreddy144/ecom-apigateway:latest
    container_name: apigateway
    depends_on:
      - eurekaserver
      - authuser
      - adminapi
      - customerapi
      - productapi
      - cartapi
      - orderapi
    ports:
      - "8081:8080"   # ðŸ‘ˆ changed because Jenkins uses 8080
    networks:
      - ecommerce-network

volumes:
  microservice-db-data:
  security-db-data:

networks:
  ecommerce-network:
